// Package internal contains generated code. DO NOT EDIT.
package internal

// Code generated by oapi-codegen. Committed output is what corroborates the
// go:generate directive as live.

type ServerInterface interface {
	ListWidgets(w http.ResponseWriter, r *http.Request)
	CreateWidget(w http.ResponseWriter, r *http.Request)
}
